export const LOAD_ERRORS_SUCCESS = 'LOAD_ERRORS_SUCCESS';
export const SET_REPORT_OPRIONS = 'SET_REPORT_OPRIONS';
export const SET_REPORT_TYPE = 'SET_REPORT_TYPE';
export const LOAD_WARNINGS_SUCCESS = 'LOAD_WARNINGS_SUCCESS';
export const LOADING_REPORTS = 'LOADING_REPORTS';
export const DELETE_REPORTS = 'DELETE_REPORTS';