export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const SET_REPORT_OPRIONS = 'SET_REPORT_OPRIONS';
export const SET_REPORT_TYPE = 'SET_REPORT_TYPE';
export const LOADING_REPORTS = 'LOADING_REPORTS';
